# Generated by Django 5.2.6 on 2025-10-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="realese_data",
            new_name="realese_date",
        ),
    ]
