# Generated by Django 5.2.6 on 2025-12-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_realese_data_movie_realese_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="realese_date",
            new_name="release_date",
        ),
    ]
